export const fulfillmentCopy = {
  en: {
    nav: {
      home: "Home",
      services: "Services",
      about: "About Us",
      contact: "Contact",
      quote: "Get a Free Quote",
      serviceItems: [
        ["Product Sourcing", "/services#sourcing"],
        ["Quality Inspection", "/services#quality"],
        ["Warehousing & Inventory", "/services#warehousing"],
        ["Pick, Pack & Ship", "/services#fulfillment"],
        ["Branding & Packaging", "/services#branding"],
        ["Store Integration", "/services#integration"],
      ],
    },
    home: {
      eyebrow: "SOURCING · QUALITY CONTROL · BRANDING · FULFILLMENT",
      title: "Source smarter. Deliver every order like a brand.",
      lead: "One accountable team coordinates suppliers, product checks, inventory, custom packaging and tracked worldwide delivery for independent eCommerce stores.",
      primary: "Get a free quote",
      secondary: "See how it works",
      proofs: ["Human-led supplier review", "Documented quality checkpoints", "Brand-ready global delivery"],
      visualLabel: "One partner. The complete journey.",
      visualSteps: ["Source", "Inspect", "Pack", "Deliver"],
      platformTitle: "Designed for the platforms independent brands already use",
      platforms: ["Shopify", "WooCommerce", "TikTok Shop", "Amazon", "Etsy", "Custom Stores"],
      operatingProofs: [["8", "focused fulfillment services"], ["1", "accountable operating workflow"], ["3", "documented control stages"], ["Order-level", "tracking handoff"]],
      problemEyebrow: "A BETTER WAY TO FULFILL",
      problemTitle: "Stop managing five suppliers for one customer order.",
      problemLead: "We bring sourcing, quality, inventory and shipping into one accountable workflow with fewer handoffs and clearer ownership.",
      without: {
        title: "Without a fulfillment partner",
        items: ["Unclear factory pricing", "No consistent quality check", "Multiple contacts and handoffs", "Generic packaging", "Tracking shared too late"],
      },
      with: {
        title: "With JW Dropshipping",
        items: ["Vetted supplier options", "Incoming and pre-shipment QC", "One dedicated point of contact", "Brand-ready packing options", "Order and tracking visibility"],
      },
      processEyebrow: "HOW IT WORKS",
      processTitle: "A visible operating path from product link to delivered parcel.",
      processLead: "Every stage has a clear owner, approval point and handoff, so your team knows what happens next.",
      steps: [
        ["01", "Brief & scope", "Share product links, destination markets, expected volume and the service responsibilities you need."],
        ["02", "Source & approve", "Compare suitable suppliers, samples, lead times, minimum quantities and packaging options before purchase."],
        ["03", "Receive & inspect", "Goods are counted, identified by SKU and checked at the quality points agreed for your product."],
        ["04", "Store, pack & dispatch", "Inventory, packing rules and customer orders move through one documented fulfillment workflow."],
        ["05", "Track & improve", "Tracking is returned to your team and recurring exceptions are reviewed as products and volume grow."],
      ],
      servicesEyebrow: "CORE SERVICES",
      servicesTitle: "Build the operating scope your store actually needs.",
      servicesLead: "Start with one focused service or combine all eight into a coordinated order journey.",
      services: [
        ["sourcing", "Product Sourcing", "Find suitable factories, compare offers, arrange samples and negotiate production details.", "/images/fulfillment/warehouse.jpg"],
        ["quality", "Quality Inspection", "Check quantity, appearance, basic function, variants and packaging before orders leave China.", "/images/fulfillment/packing-team.jpg"],
        ["warehousing", "Warehousing & Inventory", "Receive, organize and monitor products, packaging materials and branded inventory by SKU.", "/images/fulfillment/warehouse.jpg"],
        ["fulfillment", "Pick, Pack & Ship", "Process customer orders accurately, choose the right packing method and dispatch worldwide.", "/images/fulfillment/packaging.jpg"],
        ["branding", "Branding & Packaging", "Add custom boxes, bags, labels, thank-you cards and inserts for a better unboxing experience.", "/images/fulfillment/packaging.jpg"],
        ["integration", "Store Integration", "Organize orders and tracking for Shopify, WooCommerce, marketplaces or custom workflows.", "/images/fulfillment/shipping.jpg"],
      ],
      qcEyebrow: "QUALITY BEFORE SPEED",
      qcTitle: "Every parcel represents your brand.",
      qcLead: "Our workflow is designed to catch visible issues before they become refunds, support tickets or disappointed customers.",
      qcChecks: ["Supplier and sample verification", "Incoming quantity and variant check", "Appearance and packaging inspection", "Final pick-and-pack confirmation", "Photo or issue reporting when needed"],
      teamEyebrow: "VISIBLE OPERATING EVIDENCE",
      teamTitle: "Know what will be checked, recorded and handed back.",
      teamLead: "Trust grows when the service scope, inspection evidence and order handoffs are clear before daily volume increases.",
      evidenceItems: [["01", "Approved service scope", "Sourcing, inspection, packing and shipping responsibilities are confirmed before launch."], ["02", "Quality-check evidence", "Agreed checkpoints and issue photos provide context before an affected order continues."], ["03", "Order handoff visibility", "SKU, packing and tracking information follows the order through the agreed workflow."]],
      photoPlaceholder: "Team & warehouse photography",
      videoPlaceholder: "Fulfillment process video",
      faqEyebrow: "NEED MORE INFORMATION?",
      faqTitle: "Frequently asked questions",
      faqs: [
        ["Can you source products from 1688, Alibaba or an existing supplier?", "Yes. Send the product link or specification and we can compare factories, pricing, MOQ, lead time and available customization."],
        ["Do you inspect every product?", "The inspection scope is agreed before work starts. We can check incoming batches, product appearance, variants, packaging and order accuracy before dispatch."],
        ["Can you ship directly to individual customers?", "Yes. We can pick, pack and ship individual orders to customers in major international markets with tracking."],
        ["Can you use my logo and custom packaging?", "Yes. Options can include labels, cards, bags, boxes, inserts and other brand materials, subject to supplier MOQ and production time."],
        ["Which stores can you work with?", "We can support Shopify, WooCommerce, TikTok Shop, Amazon, Etsy and manually exported or custom order workflows."],
        ["How do I get a quote?", "Share your product link, destination countries, expected order volume and packaging requirements. We will review the details and propose the next step."],
      ],
      quoteEyebrow: "START WITH A PRODUCT LINK",
      quoteTitle: "Tell us what you want to source and ship.",
      quoteLead: "Send the basics and our team will review your product, destination markets and expected order flow.",
      form: {
        name: "Full name *", email: "Work email *", phone: "WhatsApp / Phone *", store: "Store URL", product: "Product or supplier URL", volume: "Daily order volume", market: "Main destination market", message: "What do you need help with?", submit: "Request a free quote", consent: "By submitting, you agree to be contacted about your enquiry.",
      },
    },
    servicesPage: {
      eyebrow: "END-TO-END DROPSHIPPING SERVICES",
      title: "One China team for sourcing, QC and global fulfillment.",
      lead: "Build the service scope your store needs today, then expand it as orders grow.",
      cardTitle: "Complete operational support",
      cardLead: "From the first supplier search to the final tracking update.",
      cardPoints: ["Flexible service scope", "Clear quality checkpoints", "Human communication", "Global delivery planning"],
      sectionTitle: "Services built around the full order journey",
      workflowTitle: "What happens after you send a product link",
      workflow: [
        ["Discovery", "We confirm product, market, volume, budget and brand requirements."],
        ["Sourcing", "Factories, quotations, MOQ, samples and production options are compared."],
        ["Preparation", "Packaging, SKU data, inventory and order handoff rules are agreed."],
        ["Operations", "Goods are received, checked, stored, picked and packed for each order."],
        ["Delivery", "The shipping route is selected and tracking is shared back to your team."],
      ],
      compareTitle: "Use only what your business needs",
      compare: [
        ["Testing products", "Sourcing, samples, basic QC and direct shipping."],
        ["Growing store", "Inventory storage, daily fulfillment, tracking and dedicated support."],
        ["Building a brand", "Private label, custom packaging, inserts and repeat production."],
        ["Scaling operations", "Multi-SKU inventory, structured order flows and shipping optimization."],
      ],
      cta: "Let’s design the right fulfillment workflow for your store.",
    },
    aboutPage: {
      eyebrow: "ABOUT JW DROPSHIPPING",
      title: "Your operations team on the ground in China.",
      lead: "We help overseas eCommerce teams turn China sourcing and fulfillment into a clear, accountable daily operation.",
      cardTitle: "Local execution. Global perspective.",
      cardLead: "A practical bridge between factories, warehouses, shipping lines and your customers.",
      cardPoints: ["Supplier coordination", "Warehouse execution", "Quality visibility", "English & Chinese communication"],
      storyEyebrow: "WHY WE EXIST",
      storyTitle: "Independent brands deserve more than a tracking number.",
      storyLead: "When sourcing, inspection and shipping are split between different contacts, small issues quickly become customer problems. JW Dropshipping puts one responsible team around the complete order journey.",
      values: [
        ["Clarity", "Clear scope, clear checkpoints and useful updates."],
        ["Ownership", "We follow issues across suppliers, warehouse and delivery handoffs."],
        ["Quality", "Speed matters only when the correct product leaves in the correct condition."],
        ["Partnership", "The workflow should adapt as your products, markets and order volume change."],
      ],
      teamTitle: "Meet the real team behind your fulfillment",
      teamLead: "Add your own team portraits, warehouse walkthroughs and daily-operation videos here before the final marketing launch.",
      operationsTitle: "What working with us should feel like",
      operations: ["One consistent point of contact", "Decisions documented before production", "Issues reported with context and options", "Operational improvements as volume grows"],
      cta: "Talk to the team that will handle your orders.",
    },
    footer: {
      lead: "China sourcing, quality control and global fulfillment for independent eCommerce brands.",
      services: "Services", company: "Company", contact: "Get Started", rights: "© 2026 JW Dropshipping. All rights reserved.",
    },
    thanks: { title: "Thank you — we received your request.", text: "Our team will review your product and store details and contact you with the next step.", button: "Back to home" },
  },
  zh: {
    nav: {
      home: "首页", services: "服务", about: "关于我们", quote: "获取免费报价",
      serviceItems: [["产品采购", "/zh/services#sourcing"], ["质量检验", "/zh/services#quality"], ["仓储与库存", "/zh/services#warehousing"], ["拣货、包装与发货", "/zh/services#fulfillment"], ["品牌与包装", "/zh/services#branding"], ["店铺订单对接", "/zh/services#integration"]],
    },
    home: {
      eyebrow: "中国采购 · 全球履约",
      title: "从中国工厂，直达海外消费者手中。",
      lead: "我们为海外独立站品牌提供产品采购、批次质检、库存管理、订单包装和全球发货服务。",
      primary: "获取免费报价", secondary: "了解服务流程",
      proofs: ["工厂直采", "发货前质量检查", "每个订单均可追踪"],
      visualLabel: "一个团队，负责完整链路。", visualSteps: ["采购", "质检", "包装", "送达"],
      platformTitle: "服务面向全球销售的独立站商家", platforms: ["Shopify", "WooCommerce", "TikTok Shop", "Amazon", "Etsy", "自建商城"],
      problemEyebrow: "更高效的履约方式", problemTitle: "不再为一个客户订单协调多个供应商。", problemLead: "我们把采购、质量、库存和物流整合为一套在中国落地执行的清晰流程。",
      without: { title: "缺少履约团队时", items: ["工厂报价不透明", "缺少稳定质检", "多人沟通、反复交接", "使用普通包装", "物流单号反馈不及时"] },
      with: { title: "与 JW Dropshipping 合作", items: ["提供合适的供应商选择", "入库和发货前双重检查", "统一对接负责人", "支持品牌化包装", "订单与物流状态清晰可查"] },
      processEyebrow: "服务流程", processTitle: "从产品链接到消费者收货，每一步都清晰可见。", processLead: "每个阶段都有明确负责人、质量检查点和下一步行动。",
      steps: [["01", "提交产品信息", "发送 AliExpress、1688、Alibaba 或供应商链接，并说明销售市场和订单量。"], ["02", "采购与比价", "筛选合适工厂，对比价格、交期、起订量和定制能力。"], ["03", "样品与方案确认", "确认样品、包装方式和预计落地成本后再推进采购。"], ["04", "入库与质检", "货物到达中国仓库后，检查数量、外观、功能和包装情况。"], ["05", "库存与订单同步", "按 SKU 管理库存，并接收独立站或销售平台的订单信息。"], ["06", "拣货、包装与品牌化", "核对产品规格，添加卡片或定制包装，完成出口包裹准备。"], ["07", "全球发货与追踪", "选择合适物流渠道，发往消费者并同步物流单号。"]],
      servicesEyebrow: "核心服务", servicesTitle: "覆盖产品发现到最终交付的完整服务。", servicesLead: "可以选择单项服务，也可以由我们管理店铺的整条供应链。",
      services: [["sourcing", "产品采购", "寻找合适工厂、比较报价、安排样品并协调生产细节。", "/images/fulfillment/warehouse.jpg"], ["quality", "质量检验", "在产品离开中国前检查数量、外观、基本功能、规格和包装。", "/images/fulfillment/packing-team.jpg"], ["warehousing", "仓储与库存", "按 SKU 接收、整理和管理产品、包材及品牌库存。", "/images/fulfillment/warehouse.jpg"], ["fulfillment", "拣货、包装与发货", "准确处理客户订单，选择合适包装，并发往全球市场。", "/images/fulfillment/packaging.jpg"], ["branding", "品牌与包装", "支持定制盒、袋、标签、感谢卡和插页，提升开箱体验。", "/images/fulfillment/packaging.jpg"], ["integration", "店铺订单对接", "支持 Shopify、WooCommerce、平台订单或自定义订单流程。", "/images/fulfillment/shipping.jpg"]],
      qcEyebrow: "质量优先", qcTitle: "每个包裹都代表您的品牌。", qcLead: "通过清晰的检查流程，尽量在问题变成退款、售后或差评之前发现并处理。",
      qcChecks: ["供应商和样品确认", "入库数量与规格检查", "产品外观与包装检查", "拣货包装最终核对", "必要时提供照片和异常报告"],
      teamEyebrow: "真实团队，真实运营", teamTitle: "让客户看见订单背后的团队。", teamLead: "这里预留给您的真实团队、仓库照片和工作视频。真实素材比网图人物更能建立信任。", photoPlaceholder: "团队与仓库实拍", videoPlaceholder: "履约流程视频",
      faqEyebrow: "需要了解更多？", faqTitle: "常见问题",
      faqs: [["可以从 1688、Alibaba 或现有供应商采购吗？", "可以。发送产品链接或规格后，我们可以比较工厂、价格、起订量、交期和定制能力。"], ["每件产品都会质检吗？", "质检范围会在合作前确认，可包含批次入库、外观、规格、包装和发货订单准确性检查。"], ["可以直接发货给海外消费者吗？", "可以。我们可以按订单拣货、包装，并通过可追踪物流发往主要国际市场。"], ["可以使用我的 Logo 和定制包装吗？", "可以，支持标签、卡片、袋、盒和插页等方案，具体取决于供应商起订量和生产时间。"], ["支持哪些店铺平台？", "可支持 Shopify、WooCommerce、TikTok Shop、Amazon、Etsy，以及人工导出或自定义订单流程。"], ["如何获取报价？", "请提供产品链接、目的国家、预计订单量和包装要求，我们会评估并给出下一步方案。"]],
      quoteEyebrow: "从一个产品链接开始", quoteTitle: "告诉我们您想采购和发货的产品。", quoteLead: "提交基本信息后，我们会评估产品、目的市场和预计订单流程。",
      form: { name: "姓名 *", email: "工作邮箱 *", phone: "WhatsApp / 电话 *", store: "店铺网址", product: "产品或供应商链接", volume: "日订单量", market: "主要目的市场", message: "您需要哪些帮助？", submit: "申请免费报价", consent: "提交即表示您同意我们就本次咨询与您联系。" },
    },
    servicesPage: {
      eyebrow: "端到端一件代发服务", title: "一个中国团队，负责采购、质检和全球履约。", lead: "先搭建适合当前阶段的服务范围，再随订单增长逐步扩展。",
      cardTitle: "完整运营支持", cardLead: "从首次供应商搜索到最终物流单号同步。", cardPoints: ["灵活服务范围", "明确质量检查点", "人工沟通", "全球物流规划"],
      sectionTitle: "围绕完整订单链路设计的服务", workflowTitle: "提交产品链接后会发生什么",
      workflow: [["需求确认", "确认产品、市场、订单量、预算和品牌要求。"], ["供应商采购", "比较工厂、报价、起订量、样品和生产方案。"], ["履约准备", "确认包装、SKU、库存和订单交接规则。"], ["日常运营", "完成收货、质检、仓储、拣货和订单包装。"], ["全球交付", "选择物流路线，并把追踪信息同步给您的团队。"]],
      compareTitle: "按业务阶段选择所需服务", compare: [["产品测试", "采购、样品、基础质检和单件直发。"], ["成长中店铺", "库存管理、日常履约、物流追踪和专人支持。"], ["品牌建设", "贴牌、定制包装、插页和重复生产管理。"], ["规模化运营", "多 SKU 库存、标准化订单流程和物流优化。"]], cta: "一起为您的店铺设计合适的履约流程。",
    },
    aboutPage: {
      eyebrow: "关于 JW DROPSHIPPING", title: "您在中国本地的供应链运营团队。", lead: "帮助海外电商团队把中国采购与全球履约变成清晰、可靠的日常运营。",
      cardTitle: "本地执行，全球视角。", cardLead: "连接工厂、仓库、物流渠道和海外消费者。", cardPoints: ["供应商协调", "仓库执行", "质量可见", "中英文沟通"],
      storyEyebrow: "我们的出发点", storyTitle: "独立品牌需要的不只是一个物流单号。", storyLead: "当采购、质检和发货由不同联系人负责时，小问题很快会变成客户问题。JW Dropshipping 希望用一个负责到底的团队，管理完整订单链路。",
      values: [["清晰", "明确范围、检查节点和有效更新。"], ["负责", "持续跟进供应商、仓库和物流交接中的问题。"], ["质量", "只有正确产品以正确状态发出时，速度才有意义。"], ["合作", "流程应随产品、市场和订单量变化而调整。"]],
      teamTitle: "认识真正负责履约的团队", teamLead: "正式推广前，可在这里加入真实团队肖像、仓库参观和日常工作视频。", operationsTitle: "合作体验应该是什么样", operations: ["固定统一联系人", "生产前记录关键决定", "异常反馈包含背景与解决选项", "随订单增长持续优化运营"], cta: "联系真正负责您订单的团队。",
    },
    footer: { lead: "为海外独立站品牌提供中国采购、质量检验和全球履约服务。", services: "服务", company: "公司", contact: "开始合作", rights: "© 2026 JW Dropshipping. 保留所有权利。" },
    thanks: { title: "感谢您的咨询，我们已收到信息。", text: "团队会评估您的产品和店铺情况，并与您沟通下一步。", button: "返回首页" },
  },
};

export function getFulfillmentCopy(lang = "en") {
  return fulfillmentCopy[lang] || fulfillmentCopy.en;
}
