const en = {
  hero: {
    dropshipAria: "Dropshipping order workflow",
    dropshipStages: [["Source", "supplier + product"], ["Check", "QC before dispatch"], ["Pack", "rules by SKU"], ["Ship", "tracking returned"]],
    warehouseFlow: "WAREHOUSE FLOW", visibleRoute: "One visible route",
    warehouseStages: ["RECEIVE", "CHECK", "STORE", "BUILD", "SHIP"],
    orderFlow: "ORDER FLOW", productReceived: "Product link received",
    orderStates: [["Supplier", "confirmed"], ["QC", "before dispatch"], ["Tracking", "returned"]],
    shortlist: "SHORTLIST BASIS", offers: "4 supplier offers",
    offerBasis: "Compared by cost, MOQ, lead time and sample notes.",
  },
  fit: {
    dropshipTitle: "Built around the operating result you need.", bestStart: "BEST STARTING POINT",
    dropshipBest: "When supplier, QC, packing and shipping need one owner.",
    dropshipLead: "Use this service when your store needs a practical operating partner behind daily direct-to-customer orders.",
    threePlTitle: "Built for daily stock movement.",
    threePlLead: "Use this service when received inventory, packing rules and dispatch updates need one organized warehouse routine.",
    threePlBest: "Inventory held in China, orders shipped one by one.",
    decisionFilter: "DECISION FILTER", orderDataFlow: "ORDER DATA FLOW", checks: "CHECKS", output: "OUTPUT",
    dropshipTags: ["Ownership", "Rules", "Branding", "Tracking"],
    threePlTags: ["Inbound", "Stock", "Packing", "Dispatch"],
  },
  qualityHero: {
    views: [["Batch-specific inspection checklist", "CHECKLIST VIEW", "JW team inspecting a product batch"], ["Photos and notes in one record", "EVIDENCE VIEW", "Warehouse package inspection evidence"], ["Pass, rework or hold", "DECISION VIEW", "Inspection record used for a release decision"]],
    inspectionItems: ["Quantity and variant", "Appearance and finish", "Packaging and label"],
    getQuote: "Get a Free Quote", seeHow: "See How It Works", tabsLabel: "Inspection evidence views",
    exampleRecord: "EXAMPLE INSPECTION RECORD", decisionReady: "Decision ready", points: "INSPECTION POINTS",
    recorded: "Recorded", available: "AVAILABLE DECISIONS", decisions: "Pass · Rework · Hold", reviewed: "REVIEWED",
  },
  warehouseZones: {
    media: [["Warehouse team receiving and registering inbound goods", "Inbound verification and sorting flow"], ["Warehouse quality-control check before stock release", "Quality control point and release check"], ["Warehouse operator completing the final dispatch scan", "Outbound dispatch and tracking handoff"]],
    controlPoint: "CONTROL POINT", active: "ACTIVE", viewZone: "VIEW ZONE",
  },
  decisionFlow: { progress: "Supplier filtering progress", steps: "Supplier filtering steps", step: "Step", active: "ACTIVE FILTER", rule: "Screening rule", validation: "Validation standard", eliminations: "Eliminations", validationText: "Checked against the shared product brief.", eliminationText: "Recorded from the actual sourcing run; no estimate is shown." },
  offers: { aria: "Example supplier offer comparison", compare: "Compare", supplier: "Supplier", price: "Unit price", moq: "MOQ", lead: "Lead time", best: "Best Match", days: "days", compareSupplier: "Compare", fields: [["Factory location", "To confirm"], ["Sample status", "Not recorded in this illustrative comparison"], ["Production capacity", "To confirm"]], selected: "suppliers selected for focused comparison", select: "Select 2–3 suppliers to focus the comparison" },
  quote: { aria: "Four quote evaluation dimensions", checklist: "CHECKLIST", checks: [["Material and finish", "Dimensions and variants", "Function requirements"], ["Unit price and MOQ", "Sample and tooling cost", "Payment conditions"], ["Lead time", "Available capacity", "Customization constraints"], ["Packaging and QC", "Parcel profile", "Shipping requirements"]] },
  detail: { zoneMap: "ZONE MAP", activeFlow: "ACTIVE FLOW", owner: "OWNER", output: "OUTPUT", owners: ["Inbound", "QC", "Inventory", "Dispatch"], outputs: ["Receipt", "Release", "Stock", "Tracking"], zoneNames: ["INBOUND", "QC", "STORAGE", "DISPATCH"], accountableRoute: "One accountable route", zonesConnected: "04 zones connected", zones: "zones", route: "route", traceable: "traceable", oneWorkflow: "ONE OPERATING WORKFLOW", oneWorkflowText: "Source, check, pack and ship with one accountable handoff.", orderControlLog: "Order control log", batch: "BATCH", sample: "SAMPLE", units: "units", unitsChecked: "Units checked", findingsOpen: "Findings open", decisionPending: "Decision pending", releaseDecision: "RELEASE DECISION", reviewRequired: "Review required before approval", dimensions: ["PRODUCT ID", "VISIBLE QUALITY", "BASIC FUNCTION", "PACKAGING"], liveRoute: "LIVE ROUTE", store: "STORE", orderData: "ORDER DATA", review: "REVIEW", warehouse: "WAREHOUSE", exceptionSafe: "THE EXCEPTION-SAFE ROUTE", batchContext: "BATCH CONTEXT", actionStream: "STANDARDIZED ACTION STREAM", outcome: "OUTCOME", readyState: "READY", faq: "SERVICE FAQ", questionsAbout: "Questions about", faqLead: "The exact scope depends on your product, markets, volume and customer promise.", qcStation: "QC STATION", inspectionActive: "Inspection active", decisionGates: "Decision gates", releaseCall: "Release call", included: "Included in plan", challenge: "THE OPERATING CHALLENGE", required: "Required inputs", ready: "Ready to scope" },
  caseStory: { challenge: "THE OPERATING CHALLENGE", evidence: "WORKING EVIDENCE" },
};

const fr = {
  hero: { dropshipAria: "Flux de commandes dropshipping", dropshipStages: [["Sourcer", "fournisseur + produit"], ["Contrôler", "CQ avant expédition"], ["Emballer", "règles par SKU"], ["Expédier", "suivi transmis"]], warehouseFlow: "FLUX D’ENTREPÔT", visibleRoute: "Un parcours visible", warehouseStages: ["RÉCEPTION", "CONTRÔLE", "STOCKAGE", "PRÉPARATION", "EXPÉDITION"], orderFlow: "FLUX DE COMMANDE", productReceived: "Lien produit reçu", orderStates: [["Fournisseur", "confirmé"], ["CQ", "avant expédition"], ["Suivi", "transmis"]], shortlist: "BASE DE PRÉSÉLECTION", offers: "4 offres fournisseurs", offerBasis: "Comparées selon le coût, le MOQ, le délai et les notes d’échantillon." },
  fit: { dropshipTitle: "Conçu autour du résultat opérationnel recherché.", bestStart: "MEILLEUR POINT DE DÉPART", dropshipBest: "Quand fournisseur, CQ, emballage et expédition doivent avoir un seul responsable.", dropshipLead: "Pour les boutiques qui recherchent un partenaire opérationnel pour leurs commandes quotidiennes directes aux clients.", threePlTitle: "Conçu pour les mouvements de stock quotidiens.", threePlLead: "Pour centraliser la réception, les règles d’emballage et les mises à jour d’expédition dans une routine d’entrepôt.", threePlBest: "Stock conservé en Chine, commandes expédiées à l’unité.", decisionFilter: "FILTRE DE DÉCISION", orderDataFlow: "FLUX DE DONNÉES DE COMMANDE", checks: "CONTRÔLES", output: "RÉSULTAT", dropshipTags: ["Responsabilité", "Règles", "Marque", "Suivi"], threePlTags: ["Réception", "Stock", "Emballage", "Expédition"] },
  qualityHero: { views: [["Liste de contrôle propre au lot", "VUE LISTE", "Équipe JW inspectant un lot de produits"], ["Photos et notes dans un même dossier", "VUE PREUVES", "Preuves d’inspection des colis"], ["Accepter, retravailler ou bloquer", "VUE DÉCISION", "Dossier d’inspection utilisé pour une décision de libération"]], inspectionItems: ["Quantité et variante", "Aspect et finition", "Emballage et étiquette"], getQuote: "Obtenir un devis gratuit", seeHow: "Voir le fonctionnement", tabsLabel: "Vues des preuves d’inspection", exampleRecord: "EXEMPLE DE RAPPORT D’INSPECTION", decisionReady: "Décision prête", points: "POINTS D’INSPECTION", recorded: "Enregistré", available: "DÉCISIONS POSSIBLES", decisions: "Accepter · Retravailler · Bloquer", reviewed: "VÉRIFIÉ" },
  warehouseZones: { media: [["Équipe d’entrepôt réceptionnant et enregistrant les marchandises", "Vérification et tri à la réception"], ["Contrôle qualité avant libération du stock", "Point de contrôle qualité et décision de libération"], ["Opérateur effectuant le scan final d’expédition", "Expédition et transmission du suivi"]], controlPoint: "POINT DE CONTRÔLE", active: "ACTIF", viewZone: "VOIR LA ZONE" },
  decisionFlow: { progress: "Progression du filtrage des fournisseurs", steps: "Étapes de filtrage des fournisseurs", step: "Étape", active: "FILTRE ACTIF", rule: "Règle de sélection", validation: "Norme de validation", eliminations: "Éliminations", validationText: "Vérifié par rapport au cahier des charges commun.", eliminationText: "Enregistrées à partir de la recherche réelle, sans estimation." },
  offers: { aria: "Exemple de comparaison d’offres fournisseurs", compare: "Comparer", supplier: "Fournisseur", price: "Prix unitaire", moq: "MOQ", lead: "Délai", best: "Meilleure correspondance", days: "jours", compareSupplier: "Comparer", fields: [["Lieu de l’usine", "À confirmer"], ["État de l’échantillon", "Non renseigné dans cet exemple"], ["Capacité de production", "À confirmer"]], selected: "fournisseurs sélectionnés pour la comparaison", select: "Sélectionnez 2 à 3 fournisseurs à comparer" },
  quote: { aria: "Quatre dimensions d’évaluation du devis", checklist: "LISTE DE CONTRÔLE", checks: [["Matière et finition", "Dimensions et variantes", "Exigences fonctionnelles"], ["Prix unitaire et MOQ", "Coût d’échantillon et d’outillage", "Conditions de paiement"], ["Délai", "Capacité disponible", "Contraintes de personnalisation"], ["Emballage et CQ", "Profil du colis", "Exigences d’expédition"]] },
  detail: { zoneMap: "PLAN DES ZONES", activeFlow: "FLUX ACTIF", owner: "RESPONSABLE", output: "RÉSULTAT", owners: ["Réception", "CQ", "Stock", "Expédition"], outputs: ["Réception", "Libération", "Stock", "Suivi"], zoneNames: ["RÉCEPTION", "CQ", "STOCKAGE", "EXPÉDITION"], accountableRoute: "Un parcours sous une seule responsabilité", zonesConnected: "04 zones reliées", zones: "zones", route: "parcours", traceable: "traçable", oneWorkflow: "UN SEUL FLUX OPÉRATIONNEL", oneWorkflowText: "Sourcer, contrôler, emballer et expédier avec un relais clairement responsable.", orderControlLog: "Journal de contrôle des commandes", batch: "LOT", sample: "ÉCHANTILLON", units: "unités", unitsChecked: "Unités contrôlées", findingsOpen: "Écarts ouverts", decisionPending: "Décision en attente", releaseDecision: "DÉCISION DE LIBÉRATION", reviewRequired: "Vérification requise avant approbation", dimensions: ["IDENTITÉ PRODUIT", "QUALITÉ VISIBLE", "FONCTION DE BASE", "EMBALLAGE"], liveRoute: "PARCOURS ACTIF", store: "BOUTIQUE", orderData: "DONNÉES COMMANDE", review: "VÉRIFICATION", warehouse: "ENTREPÔT", exceptionSafe: "PARCOURS SÉCURISÉ POUR LES EXCEPTIONS", batchContext: "CONTEXTE DU LOT", actionStream: "FLUX D’ACTIONS STANDARDISÉ", outcome: "RÉSULTAT", readyState: "PRÊT", faq: "FAQ DU SERVICE", questionsAbout: "Questions sur", faqLead: "Le périmètre exact dépend de votre produit, de vos marchés, du volume et de votre promesse client.", qcStation: "POSTE DE CQ", inspectionActive: "Inspection en cours", decisionGates: "Points de décision", releaseCall: "Décision de libération", included: "Inclus dans le plan", challenge: "DÉFI OPÉRATIONNEL", required: "Informations requises", ready: "Prêt à définir" },
  caseStory: { challenge: "DÉFI OPÉRATIONNEL", evidence: "PREUVES DE TRAVAIL" },
};

const de = {
  hero: { dropshipAria: "Dropshipping-Bestellablauf", dropshipStages: [["Beschaffen", "Lieferant + Produkt"], ["Prüfen", "QS vor Versand"], ["Verpacken", "Regeln je SKU"], ["Versenden", "Tracking zurückgemeldet"]], warehouseFlow: "LAGERABLAUF", visibleRoute: "Ein sichtbarer Ablauf", warehouseStages: ["ANNAHME", "PRÜFUNG", "LAGERUNG", "KOMMISSIONIERUNG", "VERSAND"], orderFlow: "BESTELLABLAUF", productReceived: "Produktlink erhalten", orderStates: [["Lieferant", "bestätigt"], ["QS", "vor Versand"], ["Tracking", "übermittelt"]], shortlist: "AUSWAHLGRUNDLAGE", offers: "4 Lieferantenangebote", offerBasis: "Verglichen nach Kosten, MOQ, Lieferzeit und Musternotizen." },
  fit: { dropshipTitle: "Auf das gewünschte Betriebsergebnis ausgerichtet.", bestStart: "BESTER STARTPUNKT", dropshipBest: "Wenn Lieferant, QS, Verpackung und Versand einen Verantwortlichen brauchen.", dropshipLead: "Für Shops, die einen operativen Partner für tägliche Direktbestellungen benötigen.", threePlTitle: "Für tägliche Lagerbewegungen entwickelt.", threePlLead: "Für einen geordneten Ablauf bei Wareneingang, Verpackungsregeln und Versandupdates.", threePlBest: "Bestand in China, Einzelversand pro Bestellung.", decisionFilter: "ENTSCHEIDUNGSFILTER", orderDataFlow: "BESTELLDATENFLUSS", checks: "PRÜFUNGEN", output: "ERGEBNIS", dropshipTags: ["Verantwortung", "Regeln", "Branding", "Tracking"], threePlTags: ["Wareneingang", "Bestand", "Verpackung", "Versand"] },
  qualityHero: { views: [["Chargenspezifische Prüfliste", "CHECKLISTE", "JW-Team bei der Prüfung einer Produktcharge"], ["Fotos und Notizen in einem Datensatz", "NACHWEISE", "Nachweise einer Paketprüfung"], ["Freigeben, nacharbeiten oder sperren", "ENTSCHEIDUNG", "Prüfdatensatz für die Freigabeentscheidung"]], inspectionItems: ["Menge und Variante", "Aussehen und Verarbeitung", "Verpackung und Etikett"], getQuote: "Kostenloses Angebot", seeHow: "So funktioniert es", tabsLabel: "Ansichten der Prüfnachweise", exampleRecord: "BEISPIEL-PRÜFPROTOKOLL", decisionReady: "Entscheidungsbereit", points: "PRÜFPUNKTE", recorded: "Erfasst", available: "MÖGLICHE ENTSCHEIDUNGEN", decisions: "Freigeben · Nacharbeiten · Sperren", reviewed: "GEPRÜFT" },
  warehouseZones: { media: [["Lagerteam bei Annahme und Erfassung eingehender Ware", "Prüfung und Sortierung im Wareneingang"], ["Qualitätskontrolle vor Bestandsfreigabe", "Qualitätskontrollpunkt und Freigabe"], ["Mitarbeiter beim abschließenden Versandscan", "Versand und Tracking-Übergabe"]], controlPoint: "KONTROLLPUNKT", active: "AKTIV", viewZone: "BEREICH ANSEHEN" },
  decisionFlow: { progress: "Fortschritt der Lieferantenauswahl", steps: "Schritte der Lieferantenauswahl", step: "Schritt", active: "AKTIVER FILTER", rule: "Auswahlregel", validation: "Validierungsstandard", eliminations: "Ausschlüsse", validationText: "Gegen den gemeinsamen Produktbrief geprüft.", eliminationText: "Aus dem tatsächlichen Sourcing-Lauf erfasst; keine Schätzung." },
  offers: { aria: "Beispielhafter Angebotsvergleich", compare: "Vergleichen", supplier: "Lieferant", price: "Stückpreis", moq: "MOQ", lead: "Lieferzeit", best: "Beste Übereinstimmung", days: "Tage", compareSupplier: "Vergleichen", fields: [["Fabrikstandort", "Zu bestätigen"], ["Musterstatus", "In diesem Beispiel nicht erfasst"], ["Produktionskapazität", "Zu bestätigen"]], selected: "Lieferanten für den Vergleich ausgewählt", select: "2–3 Lieferanten für den Vergleich auswählen" },
  quote: { aria: "Vier Dimensionen der Angebotsbewertung", checklist: "CHECKLISTE", checks: [["Material und Verarbeitung", "Abmessungen und Varianten", "Funktionsanforderungen"], ["Stückpreis und MOQ", "Muster- und Werkzeugkosten", "Zahlungsbedingungen"], ["Lieferzeit", "Verfügbare Kapazität", "Anpassungsgrenzen"], ["Verpackung und QS", "Paketprofil", "Versandanforderungen"]] },
  detail: { zoneMap: "BEREICHSPLAN", activeFlow: "AKTIVER ABLAUF", owner: "VERANTWORTLICH", output: "ERGEBNIS", owners: ["Wareneingang", "QS", "Bestand", "Versand"], outputs: ["Eingang", "Freigabe", "Bestand", "Tracking"], zoneNames: ["WARENEINGANG", "QS", "LAGERUNG", "VERSAND"], accountableRoute: "Ein verantwortlicher Ablauf", zonesConnected: "04 Bereiche verbunden", zones: "Bereiche", route: "Ablauf", traceable: "nachverfolgbar", oneWorkflow: "EIN OPERATIVER ABLAUF", oneWorkflowText: "Beschaffung, Prüfung, Verpackung und Versand mit klarer Verantwortung.", orderControlLog: "Bestellkontrollprotokoll", batch: "CHARGE", sample: "STICHPROBE", units: "Einheiten", unitsChecked: "Einheiten geprüft", findingsOpen: "Offene Befunde", decisionPending: "Entscheidung ausstehend", releaseDecision: "FREIGABEENTSCHEIDUNG", reviewRequired: "Prüfung vor Freigabe erforderlich", dimensions: ["PRODUKTIDENTITÄT", "SICHTBARE QUALITÄT", "GRUNDFUNKTION", "VERPACKUNG"], liveRoute: "AKTIVER ABLAUF", store: "SHOP", orderData: "BESTELLDATEN", review: "PRÜFUNG", warehouse: "LAGER", exceptionSafe: "AUSNAHMESICHERER ABLAUF", batchContext: "CHARGENKONTEXT", actionStream: "STANDARDISIERTER AKTIONSABLAUF", outcome: "ERGEBNIS", readyState: "BEREIT", faq: "SERVICE-FAQ", questionsAbout: "Fragen zu", faqLead: "Der genaue Umfang hängt von Ihrem Produkt, Ihren Märkten, dem Volumen und Ihrem Kundenversprechen ab.", qcStation: "QS-STATION", inspectionActive: "Prüfung aktiv", decisionGates: "Entscheidungspunkte", releaseCall: "Freigabeentscheidung", included: "Im Plan enthalten", challenge: "OPERATIVE HERAUSFORDERUNG", required: "Benötigte Angaben", ready: "Bereit zur Planung" },
  caseStory: { challenge: "OPERATIVE HERAUSFORDERUNG", evidence: "ARBEITSNACHWEISE" },
};

const nl = {
  hero: { dropshipAria: "Dropshipping-bestelproces", dropshipStages: [["Inkopen", "leverancier + product"], ["Controleren", "QC vóór verzending"], ["Verpakken", "regels per SKU"], ["Verzenden", "tracking teruggekoppeld"]], warehouseFlow: "MAGAZIJNSTROOM", visibleRoute: "Eén zichtbaar traject", warehouseStages: ["ONTVANGEN", "CONTROLEREN", "OPSLAAN", "SAMENSTELLEN", "VERZENDEN"], orderFlow: "BESTELSTROOM", productReceived: "Productlink ontvangen", orderStates: [["Leverancier", "bevestigd"], ["QC", "vóór verzending"], ["Tracking", "teruggekoppeld"]], shortlist: "BASIS VOOR SHORTLIST", offers: "4 leveranciersoffertes", offerBasis: "Vergeleken op kosten, MOQ, doorlooptijd en voorbeeldnotities." },
  fit: { dropshipTitle: "Gebouwd rond het operationele resultaat dat u nodig hebt.", bestStart: "BESTE STARTPUNT", dropshipBest: "Wanneer leverancier, QC, verpakking en verzending één eigenaar nodig hebben.", dropshipLead: "Voor webshops die een operationele partner nodig hebben voor dagelijkse rechtstreekse klantorders.", threePlTitle: "Gebouwd voor dagelijkse voorraadbewegingen.", threePlLead: "Voor één georganiseerde magazijnroutine voor ontvangst, verpakkingsregels en verzendupdates.", threePlBest: "Voorraad in China, bestellingen één voor één verzonden.", decisionFilter: "BESLISFILTER", orderDataFlow: "BESTELGEGEVENSSTROOM", checks: "CONTROLES", output: "RESULTAAT", dropshipTags: ["Eigenaarschap", "Regels", "Branding", "Tracking"], threePlTags: ["Ontvangst", "Voorraad", "Verpakken", "Verzenden"] },
  qualityHero: { views: [["Controlelijst per batch", "CONTROLELIJST", "JW-team dat een productbatch inspecteert"], ["Foto’s en notities in één dossier", "BEWIJS", "Bewijs van pakketinspectie"], ["Goedkeuren, herstellen of blokkeren", "BESLISSING", "Inspectiedossier voor een vrijgavebeslissing"]], inspectionItems: ["Aantal en variant", "Uiterlijk en afwerking", "Verpakking en etiket"], getQuote: "Gratis offerte aanvragen", seeHow: "Bekijk hoe het werkt", tabsLabel: "Weergaven van inspectiebewijs", exampleRecord: "VOORBEELD INSPECTIERAPPORT", decisionReady: "Klaar voor beslissing", points: "INSPECTIEPUNTEN", recorded: "Vastgelegd", available: "MOGELIJKE BESLISSINGEN", decisions: "Goedkeuren · Herstellen · Blokkeren", reviewed: "GECONTROLEERD" },
  warehouseZones: { media: [["Magazijnteam dat inkomende goederen ontvangt en registreert", "Controle en sortering bij ontvangst"], ["Kwaliteitscontrole vóór vrijgave van voorraad", "Kwaliteitscontrolepunt en vrijgave"], ["Medewerker die de laatste verzendscan uitvoert", "Verzending en overdracht van tracking"]], controlPoint: "CONTROLEPUNT", active: "ACTIEF", viewZone: "BEKIJK ZONE" },
  decisionFlow: { progress: "Voortgang leveranciersselectie", steps: "Stappen leveranciersselectie", step: "Stap", active: "ACTIEF FILTER", rule: "Selectieregel", validation: "Validatienorm", eliminations: "Afwijzingen", validationText: "Gecontroleerd aan de hand van dezelfde productbrief.", eliminationText: "Vastgelegd tijdens het echte sourcingtraject; zonder schatting." },
  offers: { aria: "Voorbeeld van leveranciersoffertes", compare: "Vergelijken", supplier: "Leverancier", price: "Stukprijs", moq: "MOQ", lead: "Doorlooptijd", best: "Beste match", days: "dagen", compareSupplier: "Vergelijk", fields: [["Fabriekslocatie", "Te bevestigen"], ["Status voorbeeld", "Niet vastgelegd in deze voorbeeldvergelijking"], ["Productiecapaciteit", "Te bevestigen"]], selected: "leveranciers geselecteerd voor gerichte vergelijking", select: "Selecteer 2–3 leveranciers om te vergelijken" },
  quote: { aria: "Vier dimensies voor offertebeoordeling", checklist: "CONTROLELIJST", checks: [["Materiaal en afwerking", "Afmetingen en varianten", "Functionele eisen"], ["Stukprijs en MOQ", "Kosten voor voorbeeld en gereedschap", "Betalingsvoorwaarden"], ["Doorlooptijd", "Beschikbare capaciteit", "Maatwerkbeperkingen"], ["Verpakking en QC", "Pakketprofiel", "Verzendeisen"]] },
  detail: { zoneMap: "ZONEKAART", activeFlow: "ACTIEVE STROOM", owner: "EIGENAAR", output: "RESULTAAT", owners: ["Ontvangst", "QC", "Voorraad", "Verzending"], outputs: ["Ontvangst", "Vrijgave", "Voorraad", "Tracking"], zoneNames: ["ONTVANGST", "QC", "OPSLAG", "VERZENDING"], accountableRoute: "Eén verantwoordelijke route", zonesConnected: "04 zones verbonden", zones: "zones", route: "route", traceable: "traceerbaar", oneWorkflow: "ÉÉN OPERATIONELE WORKFLOW", oneWorkflowText: "Inkopen, controleren, verpakken en verzenden met één duidelijke overdracht.", orderControlLog: "Logboek ordercontrole", batch: "BATCH", sample: "STEEKPROEF", units: "eenheden", unitsChecked: "Eenheden gecontroleerd", findingsOpen: "Openstaande bevindingen", decisionPending: "Besluit in afwachting", releaseDecision: "VRIJGAVEBESLUIT", reviewRequired: "Controle vereist vóór goedkeuring", dimensions: ["PRODUCTIDENTITEIT", "ZICHTBARE KWALITEIT", "BASISFUNCTIE", "VERPAKKING"], liveRoute: "ACTIEVE ROUTE", store: "WEBSHOP", orderData: "ORDERGEGEVENS", review: "CONTROLE", warehouse: "MAGAZIJN", exceptionSafe: "ROUTE MET VEILIGE UITZONDERINGEN", batchContext: "BATCHCONTEXT", actionStream: "GESTANDAARDISEERDE ACTIESTROOM", outcome: "RESULTAAT", readyState: "GEREED", faq: "SERVICE-FAQ", questionsAbout: "Vragen over", faqLead: "De exacte omvang hangt af van uw product, markten, volume en klantbelofte.", qcStation: "QC-STATION", inspectionActive: "Inspectie actief", decisionGates: "Beslismomenten", releaseCall: "Vrijgavebesluit", included: "Opgenomen in plan", challenge: "OPERATIONELE UITDAGING", required: "Benodigde gegevens", ready: "Klaar om af te bakenen" },
  caseStory: { challenge: "OPERATIONELE UITDAGING", evidence: "WERKBEWIJS" },
};

const pl = {
  hero: { dropshipAria: "Przepływ zamówień dropshipping", dropshipStages: [["Pozyskanie", "dostawca + produkt"], ["Kontrola", "QC przed wysyłką"], ["Pakowanie", "zasady dla SKU"], ["Wysyłka", "przekazany tracking"]], warehouseFlow: "PRZEPŁYW MAGAZYNOWY", visibleRoute: "Jedna widoczna ścieżka", warehouseStages: ["PRZYJĘCIE", "KONTROLA", "MAGAZYN", "KOMPLETACJA", "WYSYŁKA"], orderFlow: "PRZEPŁYW ZAMÓWIENIA", productReceived: "Otrzymano link do produktu", orderStates: [["Dostawca", "potwierdzony"], ["QC", "przed wysyłką"], ["Tracking", "przekazany"]], shortlist: "PODSTAWA KRÓTKIEJ LISTY", offers: "4 oferty dostawców", offerBasis: "Porównane pod względem kosztu, MOQ, terminu i uwag do próbek." },
  fit: { dropshipTitle: "Dopasowane do oczekiwanego wyniku operacyjnego.", bestStart: "NAJLEPSZY PUNKT STARTOWY", dropshipBest: "Gdy dostawca, QC, pakowanie i wysyłka wymagają jednego opiekuna.", dropshipLead: "Dla sklepów potrzebujących partnera operacyjnego do codziennych zamówień bezpośrednich.", threePlTitle: "Zaprojektowane do codziennego przepływu zapasów.", threePlLead: "Jedna uporządkowana rutyna przyjęcia, pakowania i aktualizacji wysyłki.", threePlBest: "Towar w Chinach, zamówienia wysyłane pojedynczo.", decisionFilter: "FILTR DECYZYJNY", orderDataFlow: "PRZEPŁYW DANYCH ZAMÓWIENIA", checks: "KONTROLE", output: "WYNIK", dropshipTags: ["Odpowiedzialność", "Zasady", "Branding", "Tracking"], threePlTags: ["Przyjęcie", "Zapas", "Pakowanie", "Wysyłka"] },
  qualityHero: { views: [["Lista kontroli dla konkretnej partii", "LISTA KONTROLNA", "Zespół JW kontrolujący partię produktów"], ["Zdjęcia i notatki w jednym raporcie", "DOWODY", "Dokumentacja kontroli paczki"], ["Akceptacja, poprawka lub blokada", "DECYZJA", "Raport kontroli używany do decyzji o zwolnieniu"]], inspectionItems: ["Ilość i wariant", "Wygląd i wykończenie", "Opakowanie i etykieta"], getQuote: "Uzyskaj bezpłatną wycenę", seeHow: "Zobacz, jak to działa", tabsLabel: "Widoki dokumentacji kontroli", exampleRecord: "PRZYKŁADOWY RAPORT KONTROLI", decisionReady: "Gotowe do decyzji", points: "PUNKTY KONTROLI", recorded: "Zapisano", available: "DOSTĘPNE DECYZJE", decisions: "Akceptacja · Poprawka · Blokada", reviewed: "SPRAWDZONO" },
  warehouseZones: { media: [["Zespół magazynu przyjmuje i rejestruje towar", "Weryfikacja i sortowanie przy przyjęciu"], ["Kontrola jakości przed zwolnieniem zapasu", "Punkt kontroli jakości i zwolnienie"], ["Operator wykonuje końcowy skan wysyłki", "Wysyłka i przekazanie trackingu"]], controlPoint: "PUNKT KONTROLNY", active: "AKTYWNA", viewZone: "ZOBACZ STREFĘ" },
  decisionFlow: { progress: "Postęp selekcji dostawców", steps: "Etapy selekcji dostawców", step: "Krok", active: "AKTYWNY FILTR", rule: "Zasada selekcji", validation: "Standard weryfikacji", eliminations: "Odrzucenia", validationText: "Sprawdzone według wspólnej specyfikacji produktu.", eliminationText: "Zapisane podczas rzeczywistego procesu sourcingu; bez szacunków." },
  offers: { aria: "Przykładowe porównanie ofert dostawców", compare: "Porównaj", supplier: "Dostawca", price: "Cena jednostkowa", moq: "MOQ", lead: "Termin", best: "Najlepsze dopasowanie", days: "dni", compareSupplier: "Porównaj", fields: [["Lokalizacja fabryki", "Do potwierdzenia"], ["Status próbki", "Brak w tym przykładowym porównaniu"], ["Moce produkcyjne", "Do potwierdzenia"]], selected: "dostawców wybranych do porównania", select: "Wybierz 2–3 dostawców do porównania" },
  quote: { aria: "Cztery obszary oceny oferty", checklist: "LISTA KONTROLNA", checks: [["Materiał i wykończenie", "Wymiary i warianty", "Wymagania funkcjonalne"], ["Cena jednostkowa i MOQ", "Koszt próbki i oprzyrządowania", "Warunki płatności"], ["Termin", "Dostępne moce", "Ograniczenia personalizacji"], ["Opakowanie i QC", "Profil paczki", "Wymagania wysyłkowe"]] },
  detail: { zoneMap: "MAPA STREF", activeFlow: "AKTYWNY PRZEPŁYW", owner: "ODPOWIEDZIALNY", output: "WYNIK", owners: ["Przyjęcie", "QC", "Zapas", "Wysyłka"], outputs: ["Przyjęcie", "Zwolnienie", "Stan", "Tracking"], zoneNames: ["PRZYJĘCIE", "QC", "MAGAZYN", "WYSYŁKA"], accountableRoute: "Jedna odpowiedzialna ścieżka", zonesConnected: "04 połączone strefy", zones: "strefy", route: "ścieżka", traceable: "identyfikowalne", oneWorkflow: "JEDEN PRZEPŁYW OPERACYJNY", oneWorkflowText: "Pozyskanie, kontrola, pakowanie i wysyłka z jasno przypisaną odpowiedzialnością.", orderControlLog: "Dziennik kontroli zamówień", batch: "PARTIA", sample: "PRÓBKA", units: "sztuk", unitsChecked: "Skontrolowane sztuki", findingsOpen: "Otwarte niezgodności", decisionPending: "Decyzja oczekuje", releaseDecision: "DECYZJA O ZWOLNIENIU", reviewRequired: "Wymagana kontrola przed zatwierdzeniem", dimensions: ["IDENTYFIKACJA PRODUKTU", "JAKOŚĆ WIZUALNA", "PODSTAWOWA FUNKCJA", "OPAKOWANIE"], liveRoute: "AKTYWNA ŚCIEŻKA", store: "SKLEP", orderData: "DANE ZAMÓWIENIA", review: "KONTROLA", warehouse: "MAGAZYN", exceptionSafe: "ŚCIEŻKA BEZPIECZNA DLA WYJĄTKÓW", batchContext: "KONTEKST PARTII", actionStream: "UJEDNOLICONY PRZEPŁYW DZIAŁAŃ", outcome: "WYNIK", readyState: "GOTOWE", faq: "FAQ USŁUGI", questionsAbout: "Pytania o", faqLead: "Dokładny zakres zależy od produktu, rynków, wolumenu i obietnicy składanej klientom.", qcStation: "STANOWISKO QC", inspectionActive: "Kontrola aktywna", decisionGates: "Punkty decyzyjne", releaseCall: "Decyzja o zwolnieniu", included: "Ujęte w planie", challenge: "WYZWANIE OPERACYJNE", required: "Wymagane informacje", ready: "Gotowe do określenia zakresu" },
  caseStory: { challenge: "WYZWANIE OPERACYJNE", evidence: "DOWODY REALIZACJI" },
};

const es = {
  hero: { dropshipAria: "Flujo de pedidos de dropshipping", dropshipStages: [["Buscar", "proveedor + producto"], ["Controlar", "QC antes del envío"], ["Empaquetar", "reglas por SKU"], ["Enviar", "seguimiento devuelto"]], warehouseFlow: "FLUJO DE ALMACÉN", visibleRoute: "Una ruta visible", warehouseStages: ["RECIBIR", "CONTROLAR", "ALMACENAR", "PREPARAR", "ENVIAR"], orderFlow: "FLUJO DEL PEDIDO", productReceived: "Enlace de producto recibido", orderStates: [["Proveedor", "confirmado"], ["QC", "antes del envío"], ["Seguimiento", "devuelto"]], shortlist: "BASE DE PRESELECCIÓN", offers: "4 ofertas de proveedores", offerBasis: "Comparadas por coste, MOQ, plazo y notas de muestras." },
  fit: { dropshipTitle: "Diseñado en torno al resultado operativo que necesitas.", bestStart: "MEJOR PUNTO DE PARTIDA", dropshipBest: "Cuando proveedor, QC, embalaje y envío necesitan un único responsable.", dropshipLead: "Para tiendas que necesitan un socio operativo para sus pedidos diarios directos al cliente.", threePlTitle: "Diseñado para el movimiento diario de inventario.", threePlLead: "Una rutina de almacén organizada para recepción, reglas de embalaje y actualizaciones de envío.", threePlBest: "Inventario en China, pedidos enviados uno por uno.", decisionFilter: "FILTRO DE DECISIÓN", orderDataFlow: "FLUJO DE DATOS DEL PEDIDO", checks: "CONTROLES", output: "RESULTADO", dropshipTags: ["Responsabilidad", "Reglas", "Marca", "Seguimiento"], threePlTags: ["Recepción", "Inventario", "Embalaje", "Envío"] },
  qualityHero: { views: [["Lista de control específica del lote", "LISTA DE CONTROL", "Equipo de JW inspeccionando un lote"], ["Fotos y notas en un solo registro", "EVIDENCIAS", "Evidencias de inspección del paquete"], ["Aprobar, corregir o retener", "DECISIÓN", "Registro de inspección para decidir la liberación"]], inspectionItems: ["Cantidad y variante", "Aspecto y acabado", "Embalaje y etiqueta"], getQuote: "Solicita un presupuesto gratuito", seeHow: "Descubre cómo funciona", tabsLabel: "Vistas de evidencias de inspección", exampleRecord: "EJEMPLO DE INFORME DE INSPECCIÓN", decisionReady: "Listo para decidir", points: "PUNTOS DE INSPECCIÓN", recorded: "Registrado", available: "DECISIONES DISPONIBLES", decisions: "Aprobar · Corregir · Retener", reviewed: "REVISADO" },
  warehouseZones: { media: [["Equipo de almacén recibiendo y registrando mercancía", "Verificación y clasificación de entrada"], ["Control de calidad antes de liberar inventario", "Punto de control de calidad y liberación"], ["Operario completando el escaneo final de envío", "Salida y entrega del seguimiento"]], controlPoint: "PUNTO DE CONTROL", active: "ACTIVA", viewZone: "VER ZONA" },
  decisionFlow: { progress: "Progreso del filtrado de proveedores", steps: "Pasos del filtrado de proveedores", step: "Paso", active: "FILTRO ACTIVO", rule: "Regla de selección", validation: "Norma de validación", eliminations: "Descartes", validationText: "Comprobado con la misma ficha de producto.", eliminationText: "Registrados durante el proceso real de sourcing; sin estimaciones." },
  offers: { aria: "Ejemplo de comparación de ofertas", compare: "Comparar", supplier: "Proveedor", price: "Precio unitario", moq: "MOQ", lead: "Plazo", best: "Mejor opción", days: "días", compareSupplier: "Comparar", fields: [["Ubicación de la fábrica", "Por confirmar"], ["Estado de la muestra", "No registrado en esta comparación ilustrativa"], ["Capacidad de producción", "Por confirmar"]], selected: "proveedores seleccionados para comparar", select: "Selecciona 2–3 proveedores para comparar" },
  quote: { aria: "Cuatro dimensiones para evaluar la oferta", checklist: "LISTA DE CONTROL", checks: [["Material y acabado", "Dimensiones y variantes", "Requisitos funcionales"], ["Precio unitario y MOQ", "Coste de muestra y utillaje", "Condiciones de pago"], ["Plazo", "Capacidad disponible", "Límites de personalización"], ["Embalaje y QC", "Perfil del paquete", "Requisitos de envío"]] },
  detail: { zoneMap: "MAPA DE ZONAS", activeFlow: "FLUJO ACTIVO", owner: "RESPONSABLE", output: "RESULTADO", owners: ["Recepción", "QC", "Inventario", "Envío"], outputs: ["Recepción", "Liberación", "Inventario", "Seguimiento"], zoneNames: ["RECEPCIÓN", "QC", "ALMACENAJE", "ENVÍO"], accountableRoute: "Una ruta con un único responsable", zonesConnected: "04 zonas conectadas", zones: "zonas", route: "ruta", traceable: "trazable", oneWorkflow: "UN SOLO FLUJO OPERATIVO", oneWorkflowText: "Abastecer, revisar, empaquetar y enviar con una responsabilidad clara.", orderControlLog: "Registro de control de pedidos", batch: "LOTE", sample: "MUESTRA", units: "unidades", unitsChecked: "Unidades revisadas", findingsOpen: "Hallazgos abiertos", decisionPending: "Decisión pendiente", releaseDecision: "DECISIÓN DE LIBERACIÓN", reviewRequired: "Se requiere revisión antes de aprobar", dimensions: ["IDENTIDAD DEL PRODUCTO", "CALIDAD VISIBLE", "FUNCIÓN BÁSICA", "EMBALAJE"], liveRoute: "RUTA ACTIVA", store: "TIENDA", orderData: "DATOS DEL PEDIDO", review: "REVISIÓN", warehouse: "ALMACÉN", exceptionSafe: "RUTA SEGURA PARA EXCEPCIONES", batchContext: "CONTEXTO DEL LOTE", actionStream: "FLUJO DE ACCIONES ESTANDARIZADO", outcome: "RESULTADO", readyState: "LISTO", faq: "PREGUNTAS DEL SERVICIO", questionsAbout: "Preguntas sobre", faqLead: "El alcance exacto depende de su producto, mercados, volumen y promesa al cliente.", qcStation: "PUESTO DE QC", inspectionActive: "Inspección activa", decisionGates: "Puntos de decisión", releaseCall: "Decisión de liberación", included: "Incluido en el plan", challenge: "RETO OPERATIVO", required: "Datos necesarios", ready: "Listo para definir el alcance" },
  caseStory: { challenge: "RETO OPERATIVO", evidence: "EVIDENCIAS DEL TRABAJO" },
};

const content = { en, fr, de, nl, pl, es };

export function getServiceUi(locale = "en") {
  return content[locale] || content.en;
}
